---
- name: Configure Kubernetes Nodes
  hosts: all
  become: true
  tasks:
    - name: Update apt cache and upgrade all packages
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist

    - name: Disable swap for current session
      ansible.builtin.command:
        cmd: swapoff -a
      become: true
      changed_when: false

    - name: Disable swap permanently, persist reboots
      ansible.builtin.replace:
        path: /etc/fstab
        regexp: '^(\s*)([^#\n]+\s+)(\w+\s+)swap(\s+.*)$'
        replace: '#\1\2\3swap\4'
        backup: true

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - curl
          - apt-transport-https
          - ca-certificates
          - docker.io
        state: present

    - name: Ensure Docker is at latest version
      ansible.builtin.apt:
        name: docker.io
        state: fixed

    - name: Ensure Docker service is running and enabled
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Add current user to docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true

    - name: Configure kernel parameters for Kubernetes
      ansible.builtin.command: sysctl -w "{{ item.name }}={{ item.value }}"
      check_mode: true
      changed_when: false
      with_items:
        - { name: 'net.bridge.bridge-nf-call-iptables', value: 1 }
        - { name: 'net.bridge.bridge-nf-call-ip6tables', value: 1 }
        - { name: 'net.ipv4.ip_forward', value: 1 }

    - name: Ensure kernel parameters persist on reboot
      ansible.builtin.lineinfile:
        path: /etc/sysctl.conf
        state: present
        line: "{{ item.name }} = {{ item.value }}"
      with_items:
        - { name: 'net.bridge.bridge-nf-call-iptables', value: 1 }
        - { name: 'net.bridge.bridge-nf-call-ip6tables', value: 1 }
        - { name: 'net.ipv4.ip_forward', value: 1 }

    - name: Reload sysctl to apply changes
      ansible.builtin.command:
        cmd: sysctl -p
      changed_when: false
